#include "stopwords.h"
#include "ui_stopwords.h"
#include <QListView>
StopWords::StopWords(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::StopWords)
{
    ui->setupUi(this);
ui->listWidget->addItem("i");
ui->listWidget->addItem("me");
ui->listWidget->addItem("myself");
ui->listWidget->addItem("my");
ui->listWidget->addItem("we");
ui->listWidget->addItem("ours");
ui->listWidget->addItem("our");
ui->listWidget->addItem("ourselves");
ui->listWidget->addItem("you");
ui->listWidget->addItem("your");
ui->listWidget->addItem("yours");
ui->listWidget->addItem("yourself");
ui->listWidget->addItem("yourselves");
ui->listWidget->addItem("he");
ui->listWidget->addItem("him");
ui->listWidget->addItem("his");
ui->listWidget->addItem("himself");
ui->listWidget->addItem("she");
ui->listWidget->addItem("her");
ui->listWidget->addItem("hers");
ui->listWidget->addItem("herself");
ui->listWidget->addItem("it");
ui->listWidget->addItem("its");
ui->listWidget->addItem("itself");
ui->listWidget->addItem("they");
ui->listWidget->addItem("them");
ui->listWidget->addItem("their");
ui->listWidget->addItem("theirs");
ui->listWidget->addItem("themselves");
ui->listWidget->addItem("what");
ui->listWidget->addItem("which");
ui->listWidget->addItem("who");
ui->listWidget->addItem("whom");
ui->listWidget->addItem("this");
ui->listWidget->addItem("that");
ui->listWidget->addItem("these");
ui->listWidget->addItem("those");
ui->listWidget->addItem("am");
ui->listWidget->addItem("is");
ui->listWidget->addItem("are");
ui->listWidget->addItem("was");
ui->listWidget->addItem("were");
ui->listWidget->addItem("be");
ui->listWidget->addItem("been");
ui->listWidget->addItem("being");
ui->listWidget->addItem("have");
ui->listWidget->addItem("has");
ui->listWidget->addItem("had");
ui->listWidget->addItem("having");
ui->listWidget->addItem("do");
ui->listWidget->addItem("does");
ui->listWidget->addItem("did");
ui->listWidget->addItem("doing");
ui->listWidget->addItem("a");
ui->listWidget->addItem("an");
ui->listWidget->addItem("the");
ui->listWidget->addItem("and");
ui->listWidget->addItem("but");
ui->listWidget->addItem("if");
ui->listWidget->addItem("or");
ui->listWidget->addItem("because");
ui->listWidget->addItem("as");
ui->listWidget->addItem("until");
ui->listWidget->addItem("while");
ui->listWidget->addItem("of");
ui->listWidget->addItem("at");
ui->listWidget->addItem("by");
ui->listWidget->addItem("for");
ui->listWidget->addItem("with");
ui->listWidget->addItem("about");
ui->listWidget->addItem("against");
ui->listWidget->addItem("between");
ui->listWidget->addItem("into");
ui->listWidget->addItem("through");
ui->listWidget->addItem("during");
ui->listWidget->addItem("before");
ui->listWidget->addItem("after");
ui->listWidget->addItem("above");
ui->listWidget->addItem("below");
ui->listWidget->addItem("to");
ui->listWidget->addItem("from");
ui->listWidget->addItem("up");
ui->listWidget->addItem("down");
ui->listWidget->addItem("in");
ui->listWidget->addItem("out");
ui->listWidget->addItem("off");
ui->listWidget->addItem("over");
ui->listWidget->addItem("under");
ui->listWidget->addItem("again");
ui->listWidget->addItem("further");
ui->listWidget->addItem("then");
ui->listWidget->addItem("once");
ui->listWidget->addItem("here");
ui->listWidget->addItem("there");
ui->listWidget->addItem("when");
ui->listWidget->addItem("where");
ui->listWidget->addItem("why");
ui->listWidget->addItem("how");
ui->listWidget->addItem("all");
ui->listWidget->addItem("any");
ui->listWidget->addItem("both");
ui->listWidget->addItem("each");
ui->listWidget->addItem("few");
ui->listWidget->addItem("more");
ui->listWidget->addItem("most");
ui->listWidget->addItem("other");
ui->listWidget->addItem("some");
ui->listWidget->addItem("such");
ui->listWidget->addItem("no");
ui->listWidget->addItem("nor");
ui->listWidget->addItem("not");
ui->listWidget->addItem("only");
ui->listWidget->addItem("own");
ui->listWidget->addItem("same");
ui->listWidget->addItem("so");
ui->listWidget->addItem("than");
ui->listWidget->addItem("too");
ui->listWidget->addItem("very");
ui->listWidget->addItem("can");
ui->listWidget->addItem("will");
ui->listWidget->addItem("just");
ui->listWidget->addItem("don");
ui->listWidget->addItem("should");
ui->listWidget->addItem("now");
}

StopWords::~StopWords()
{
    delete ui;
}

void StopWords::on_CloseButton_clicked()
{
    close();
}



